Repository oduwsdl/MementoEmbed, pull requests merged in 2018-07, with the labels that each got.

#71 Docker deployment with waitress
  Dockerfile
  config/default.py
  docker_appconfig.json
  dockerstart.sh
  instance/application.cfg
  mementoembed/__init__.py
  mementoembed/archiveresource.py
  mementoembed/favicon.py
  mementoembed/imageselection.py
  mementoembed/mementoresource.py
  mementoembed/mementosurrogate.py
  mementoembed/originalresource.py
  mementoembed/resources/easylist_adservers.txt
  mementoembed/resources/easylist_adservers_popup.txt
  mementoembed/resources/easylist_general_block.txt
  mementoembed/textprocessing.py
  tests/test_archiveresource.py
  tests/test_favicon.py
  tests/test_originalresource.py
Labels: enhancement

#73 Meta redirect error from cnn
  instance/application.cfg
  mementoembed/mementoresource.py
Labels: bug

#74 Hash style urims for Perma.cc
  mementoembed/favicon.py
  mementoembed/mementoresource.py
  tests/test_favicon.py
  tests/test_mementoresource.py
  tests/test_originalresource.py
Labels: bug, requirement

#80 Rename manifest file to uppercase for strict loading requirement
  Dockerfile
  MANIFEST.in
Labels: bug

#82 assorted Dockerfile improvements from @ibnesayeed, fixes #81
  Dockerfile
  sample_appconfig.json
Labels: enhancement

#84 This addresses issues where pressing enter reset the form, fixes #76
  mementoembed/templates/index.html
Labels: bug

#92 address issues with timeout errors, meta redirects, and image and favicon download problems
  config/default.py
  instance/application.cfg
  mementoembed/__init__.py
  mementoembed/cachesession.py
  mementoembed/favicon.py
  mementoembed/imageselection.py
  mementoembed/mementoresource.py
  mementoembed/mementosurrogate.py
  sample_appconfig.json
  tests/test_imageselection.py
  tests/uritestlist.txt
Labels: bug

#108 fixes #60, now there is an error template so that users still see the header/footer even when they get a 404
  mementoembed/__init__.py
  mementoembed/templates/generic_error.html
Labels: enhancement

#112 Prefer for thumbnails
  Dockerfile
  config/default.py
  docs/source/conf.py
  docs/source/web_api.rst
  mementoembed/cachesession.py
  mementoembed/mementoresource.py
  mementoembed/mementothumbnail.py
  mementoembed/services/errors.py
  mementoembed/services/product.py
  mementoembed/static/images/downarrow.png
  mementoembed/templates/generate_thumbnail.html
  mementoembed/templates/index.html
  mementoembed/templates/oldindex.html
  mementoembed/ui/__init__.py
  mementoembed/ui/product.py
  mementoembed/version.py
  package-lock.json
  raiseversion.sh
Labels: enhancement

#113 Social card improvements
  config/default.py
  mementoembed/imageselection.py
  mementoembed/services/errors.py
  mementoembed/services/memento.py
  mementoembed/services/product.py
  mementoembed/static/js/mementoembed.js
  mementoembed/templates/about.html
  mementoembed/templates/generate_social_card.html
  mementoembed/templates/generate_thumbnail.html
  mementoembed/templates/index.html
  mementoembed/templates/navbar_menu.html
  mementoembed/templates/new_social_card.html
  mementoembed/templates/social_card_htmlonly.html
  mementoembed/ui/product.py
  sample_appconfig.cfg
Labels: bug, enhancement
